### ISSUE TITLE
Confusion with discrepancy between training and testing

### ISSUE THREAD

**Issue by pbalaji98** [michhar/pytorch-yolo-v3-custom#3] opened 2019-08-05 20:45 UTC
Hello,

Thank you for providing the pytorch implementation of YOLO to detect custom objects! I've run into a major issue where my training set garners a loss of < 1 after training with 700-1000 images, but when testing images of the same type, I get rather wacky results that don't make much sense. I don't really have a deep understanding of YOLO, or even NN, to really get understanding of why this is happening. Any help is appreciated.

**Comment by michhar** [comment] 2019-08-06 14:56
Hello @pbalaji98 - thank you for trying this out.  It's definitely a WIP.  I, too, saw `eval.py` was giving some strange results.  Please allow me to look into this and post results back to your issue.  In the meantime, 
* could you provide more info?  
* Is it `eval.py`?  
* Is it drawing many, tiny bounding boxes?  
* Have you tried `live.py`?  

One issue I've seen is that the algorithm (with fine-tuning) is very sensitive to various hyperparams such as LR and amount of layers to "unfreeze" and overfits easily.  You could always try 
* the `intermediate` or even earlier models produced in `eval.py` or `live.py`
* When training, could try an "unfreeze" argument of 2 (or play with this) 
* modifying the `FINE_TUNE_STOP_LAYER = layers_length - 5 # int(layers_length/1.3)` line in `train.py` to be more or less as an experiment

Please let me know if you find out an issues/resolutions.  Ty!

**Comment by pbalaji98** [comment] 2019-08-06 17:04
Sure, I can provide you more info. Thank you for taking the time to look
into this.

Looking at the loss as a function of iteration, it seems that the network
is training moderately on my images. I've included a graph of the loss as a
function of iteration (images). I trained with 1000 images., but after 200,
it seems that the loss fluctuates and doesn't really settle. I am assuming
that I can better this by making alterations to the learning step and batch
size, so I'm not too sure there is any issue there.

After training, I used eval.py on my testing set. What is happening indeed
is that many tiny bounding boxes are being drawn. I provided images for
what I am looking for and what is happening. By the looks of the bounding
boxes, it seems that the original dimensions of the image are not being
taken into consideration, although eval.py does look like it's resizing the
inputted image to match with the model. (I have to admit that I have not
looked at the code too closely, since I just started working on it). My
inputted image is 722 x 364, but it seems to me that eval.py only draws
bounding boxes in a 416 x 416 space. Approximately half of the bounding
boxes drawn (~2500) have an objectness score of > 0.5, which confuses me as
well since my images only have 1-20 objects in them.

I have not tried live.py, but I will look into it. I'll also try the
recommendations you gave.

Regards,
Praveen

**Comment by pbalaji98** [comment] 2019-08-07 03:48
Just to provide more information, I'm using the anchor values given in the
configuration file yolov3-1class.cfg. I tried running kmeans on my set in
get new order anchor boxes, but for some reason, I wasn't receiving any
output.

**Comment by ymaillet** [comment] 2019-08-28 12:13
Hello, 

First of all i would like to thank you for this implementation of YOLO.
I have the same issue than pbalaji98 : good training error ( approximately 0.5, 2 classes, 200 images) but the bounding boxes are not working correctly (as you said, it is drawing many, tiny bounding boxes).
I have used kmeans to generate custom anchor boxes.

I'll try to change some parameters (froozen layers...) and let you know if i have some updates :)

pbalaji98 have you made any progress on your side?

**Comment by ymaillet** [comment] 2019-09-02 09:07
Hi !

I have made some tests (on 3 classes, i modified everything properly)  and i still have the same problem :
I got a loss of 0.03 on the training set.  eval.py outputs are really strange (on the test set AND on the training set)  : 
- Sometimes i have a overlap of >0.5 but i can't see it on the picture (just many tiny boxes)
- The prediction (in write_results from utils) for classes has the same pattern everytime : [~0.5, 0.0000, ~0.5]. The "0.0000" really bothers me, it looks like there's a mistake somewhere.

Note that i didn't train it very long ( 2 unfrozen layers) but still, a loss of 0.03 SHOULD bring some results on the training set imo.

I have another question : How many classes does the YOLOv3 weight file is supposed to detect (originally) ?

Have a nice day !

**Comment by michhar** [comment] 2019-09-02 23:13
Hi @ymaillet!  Thank you for testing.  I've only tested with 1 and 2 classes so far.  My initial assessment has yielded better results is that the model is being trained incorrectly due to scaling the ground truth boxes so the loss function is optimizing to the wrong scale, hence tiny boxes.  I believe in this function:

https://github.com/michhar/pytorch-yolo-v3-custom/blob/master/customloader.py#L21

there needs to be a rescale up to the model dimension (416).  I've been testing and this seems to be the fix, however having a few other issues diagnosing right now for different class numbers.  So please bear with me for a bit longer - I'll check something in soon for you to try.

Originally, the YOLOv3 weights file detects **80 classes**.

Have a great day!

**Comment by ymaillet** [comment] 2019-09-03 14:02
Hi !

Here what's bother me today after some research : 

In customloader.py, we use
`boxes = boxes[:, 1:]
....
category_ids = np.array(boxes_[:,0]).reshape(-1,1)
ground_truth = np.concatenate([boxes, category_ids], 1).reshape(-1,5)
`
at the first line we are replacing the variable boxes, which mean me double the information during the concatenate operation after.   
Exemple :
Before **transform_annotation** : [2 0.4 0.3 0.6 0.7]
After **transform_annotation** : [0.4 0.3 0.6 0.7 0.4]
But shouldn't the intented output be [0.4 0.3 0.6 0.7 2] ? 
( just have to create another variable to store the original boxes if it's the case)


Then i don't fully understand what transformation the ground truth goes through from line 274 to 290 (https://github.com/michhar/pytorch-yolo-v3-custom/blob/c0638d62bf3f6b0f864c72a9062edc50ca2515da/customloader.py#L274) ... i understand we have to map the Bounding box to be able to use it as a loss, but i don't understand all the changes :
before line 274 --> BB :  [[1.3346127 1.7032423 1.7707713 2.783908  2.  ]]
after line 290 (by finding the correct row ) --> BB :  [[-1.6082869  -1.30750118 -2.64746063 -3.44205246  1.          2.   ]]
So, i agree with the need of a mapping, i  agree with the need of adding the confidence to the bouding box (1. in example), but i don't get the other changes.... Could you explain it to me please  ? 

Again thank you for the efforts you are putting in this implementation !

Have a nice day

**Comment by ymaillet** [comment] 2019-09-04 13:52
Hi, 

By searching a little bit i understand the transformation of the GT : in practice we have to use the log function to avoid gradient problems, so it's normal that the bouding boxes doesn't make any sense for Humans after.

I saw another problem on custom loader : 
All the functions center-->corner or corner-->center in bbox.py have a problem :
The last 2 numbers of the boxes does not change, i think it is a memory issue (expected behaviour in python but can be confusing sometimes).
I solved this by using a deep copy  (copy.deepcopy() )

    `prediction_new = copy.deepcopy(prediction)`
    `prediction_new[:,:,0] = (prediction[:,:,0] + prediction[:,:,2])/2`
    `prediction_new[:,:,1] = (prediction[:,:,1] + prediction[:,:,3])/2`
    `prediction_new[:,:,2] = 2*(prediction[:,:,2] - prediction[:,:,0])`
    `prediction_new[:,:,3] = 2*(prediction[:,:,3] - prediction[:,:,1])`
    `return prediction_new`

and this way the boxes are converted properly.

**Comment by michhar** [comment] 2019-09-05 17:12
@ymaillet Thank you so much for your research!  Is your model appearing to converge properly?

I have pushed the changes to fix these issues on master.  Will likely move to a branch soon for the development/testing on this project as it moves forward.  It is my hobby right now, but glad to help you and receive help.

I am now, however, finding on my data for 2 classes (only 92 training images right now, `--unfreeze 2 --lr 5e-3`), it is not converging very well - although the boxes are getting drawn correctly it appears.  So, I'll be working on the convergence issues next.  

If you find anything else in your trials, please don't hesitate to add to this issue or begin a new one.  Your help has been very much appreciated!

**Comment by ymaillet** [comment] 2019-09-05 20:09
Hi, 

You are welcome, you did all the hard work aha

I have two issues :
By changing transform_annotation (custom_loader), another error appears : 
```
  File "train.py", line 275, in <module>
    loss  = YOLO_loss(ground_truth, output)
  File "train.py", line 189, in YOLO_loss
    targ_labels[:,0] = 1 - targ_labels[:,0]
  File "C:\Users\yannm\Anaconda3\lib\site-packages\torch\tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered
```
This one is with the GPU, if i switch to CPU i instead get :

```
File "train.py", line 275, in <module>
    loss  = YOLO_loss(ground_truth, output)
  File "train.py", line 183, in YOLO_loss
    cls_labels[torch.arange(gt_ob.shape[0]).long(), gt_ob[:,5].long()] = 1
IndexError: index 2 is out of bounds for dimension 1 with size 2
```

for the CPU, i didn't go deeper into the code but i notice something : the problem is when ground_truth[,:4] are >= 2

by putting  
```
    ground_truth[:,4]= 1.99
    return ground_truth
```
--> no error

```
    ground_truth[:,4]= 2
    return ground_truth
```
--> error 
Same behaviour for CPU and GPU, just doesn't print the same thing.

Definitely strange, we'll have to investigate...



Second issue (i already have it since 1week but didn't talk about it, it's GPU related) :
When i finished training (On GPU) and want to test it, i have this error :

```
  File "eval.py", line 426, in <module>
    output[i,[0,2]] -= (model_dim - scaling_factor_x[0]*orig_dim[i,0])/2
RuntimeError: expected device cuda:0 and dtype Float but got device cpu and dtype Float
```
It can be something easy to solve i guess (already had this kind of issue before and it was a float conversion to do), but i was wondering if you have experienced it before investigating ?

So to answer your question, no still didn't achieve great results because of this !
Sorry long post aha

**Comment by michhar** [comment] 2019-09-06 05:23
Hello,

For 1) have you ensured the

```
[yolo]
mask = 0,1,2
classes=3
anchors=...
```
has the correct value in each `[yolo]` module and at the `[net]` module at the top?

For 2) there's a missing `tensorxyz.to(device)` somewhere or we convert output to non-cuda tensor which would solve it likely.

Try:

`output = output.to(torch.device("cpu"))` before `output[i,[0,2]] -= (model_dim - scaling_factor_x[0]*orig_dim[i,0])/2` and you will know if the tensor mis-match is the issue.

Thanks!

**Comment by ymaillet** [comment] 2019-09-06 08:35
Hello, 

Yes my cfg file is set up correctly.
I re-clone the Project, I just change the data folder and try to train it (non GPU computer), same issue.
Don't know why you don't have the same issue but i had a problem with 
`    cls_labels[torch.arange(gt_ob.shape[0]).long(), gt_ob[:,5].long()] = 1`
So i use numpy and a loop to get things done :
```
    cls_labels = np.zeros((bs, num_classes))
    for i in range(bs):
        cls_labels[i,int(gt_ob[i,5]-1)] = 1

    cls_labels = torch.from_numpy(cls_labels).to
```
 and i obtain the format i was looking for (i believe this is what we want ?) 👍 
```
labels :  tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.]], dtype=torch.float64)
target :  tensor([[ 1.0686, -0.0686],
        [ 1.0948, -0.0948],
        [ 1.0906, -0.0906],
        [ 1.0562, -0.0562]], grad_fn=<CopySlices>)
```
To be able to compute the loss.

I'll try your solution for my GPU problem this WE, thank you

**Comment by michhar** [comment] 2020-03-07 19:26
Hope all went well.  I'm closing as this is old, but feel free to reopen if you need.

**Closed by michhar** 2020-03-07 19:26 UTC
